<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
        <UseWPF>true</UseWPF>
        <ApplicationIcon>icon\icon.ico</ApplicationIcon>
        <IsPackable>false</IsPackable>
        <AssemblyVersion>1.0.0</AssemblyVersion>
        <FileVersion>1.0.0</FileVersion>
        <NeutralLanguage>en</NeutralLanguage>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <Company>PureLogicCode.com</Company>
    </PropertyGroup>

    <ItemGroup>
        <Using Include="Serilog" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Meziantou.Analyzer" Version="3.0.190">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="MessagePack" Version="3.1.8" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    </ItemGroup>

</Project>