using System.Text;
using SimpleLauncher.Models;

namespace SimpleLauncher.Interfaces;

public interface IMessageBoxLibraryService
{
    Task TakeScreenShotMessageBox();
    Task CouldNotSaveScreenshotMessageBox();
    Task GameIsAlreadyInFavoritesMessageBox(string fileNameWithExtension);
    Task ErrorWhileAddingFavoritesMessageBox();
    Task ErrorWhileRemovingGameFromFavoriteMessageBox();
    Task ErrorOpeningTheUpdateHistoryWindowMessageBox();
    Task ErrorOpeningVideoLinkMessageBox();
    Task ProblemOpeningInfoLinkMessageBox();
    Task ErrorOpeningUrlMessageBox();
    Task ThereIsNoCoverMessageBox();
    Task ThereIsNoTitleSnapshotMessageBox();
    Task ThereIsNoGameplaySnapshotMessageBox();
    Task ThereIsNoCartMessageBox();
    Task ThereIsNoVideoFileMessageBox();
    Task CouldNotOpenManualMessageBox();
    Task NoPdfViewerInstalledMessageBox();
    Task ThereIsNoManualMessageBox();
    Task ThereIsNoWalkthroughMessageBox();
    Task ThereIsNoCabinetMessageBox();
    Task ThereIsNoFlyerMessageBox();
    Task ThereIsNoPcbMessageBox();
    Task FileSuccessfullyDeletedMessageBox(string fileNameWithExtension);
    Task FileCouldNotBeDeletedMessageBox(string fileNameWithExtension);
    Task DefaultImageNotFoundMessageBox();
    Task GlobalSearchErrorMessageBox();
    Task PleaseEnterSearchTermMessageBox();
    Task ErrorLaunchingGameMessageBox(string logPath);
    Task SelectAGameToLaunchMessageBox();
    Task FileAddedToFavoritesMessageBox(string fileNameWithoutExtension);
    Task FileRemovedFromFavoritesMessageBox(string fileNameWithoutExtension);
    Task CouldNotLaunchThisGameMessageBox(string logPath);
    Task ProtocolHandlerNotRegisteredMessageBox(string protocol);
    Task EmulatorPathNotConfiguredMessageBox();
    Task ErrorCalculatingStatsMessageBox();
    Task FailedSaveReportMessageBox();
    Task ReportSavedMessageBox();
    Task NoStatsToSaveMessageBox();
    Task ErrorLaunchingToolMessageBox(string logPath);
    Task SelectedToolNotFoundMessageBox();
    Task ErrorMessageBox();
    Task NoFavoriteFoundMessageBox();
    Task MoveToWritableFolderMessageBox();
    Task InvalidSystemConfigMessageBox();
    Task ErrorMethodLoadGameFilesAsyncMessageBox();
    Task ErrorOpeningDonationLinkMessageBox();
    Task ToggleGamepadFailureMessageBox();
    Task ToolLaunchWasCanceledByUserMessageBox();
    Task ErrorChangingViewModeMessageBox();
    Task NavigationButtonErrorMessageBox();
    Task SelectSystemBeforeSearchMessageBox();
    Task EnterSearchQueryMessageBox();
    Task ErrorWhileLoadingHelpUserXmlMessageBox();
    Task NoSystemInHelpUserXmlMessageBox();
    Task<MessageBoxResult> CouldNotLoadHelpUserXmlMessageBox();
    Task FailedToLoadHelpUserXmlMessageBox();
    Task FileHelpUserXmlIsMissingMessageBox();
    Task ErrorWhileLoadingParametersMdMessageBox();
    Task NoSystemInParametersMdMessageBox();
    Task FailedToLoadParametersMdMessageBox();
    Task FileParametersMdIsMissingMessageBox();
    Task FileParametersMdIsEmptyMessageBox();
    Task ImageViewerErrorMessageBox();
    Task ReinstallSimpleLauncherFileCorruptedMessageBox();
    Task ReinstallSimpleLauncherFileMissingMessageBox();
    Task ErrorCheckingForUpdatesMessageBox();
    Task ErrorLoadingRomHistoryMessageBox();
    Task NoHistoryXmlOrDatFoundMessageBox();
    Task ErrorOpeningBrowserMessageBox();
    Task SystemXmlIsCorruptedMessageBox(string logPath);
    Task WouldYouLikeToOpenTheLogMessageBox(string logPath);
    Task FileSystemXmlIsCorruptedMessageBox(string logPath);
    Task InstallUpdateManuallyMessageBox();
    Task UpdaterLaunchFailedMessageBox();
    Task RequiredFileMissingMessageBox();
    Task EnterSupportRequestMessageBox();
    Task EnterNameMessageBox();
    Task EnterEmailMessageBox();
    Task ApiKeyErrorMessageBox();
    Task SupportRequestSuccessMessageBox();
    Task SupportRequestSendErrorMessageBox();
    Task ExtractionFailedMessageBox();
    Task FileNeedToBeCompressedMessageBox();
    Task DownloadedFileIsMissingMessageBox();
    Task FileIsLockedMessageBox(string tempFolderPath);
    Task LinksSavedMessageBox();
    Task DeadZonesSavedMessageBox();
    Task LinksRevertedMessageBox();
    Task MainWindowSearchEngineErrorMessageBox();
    Task DownloadExtractionFailedMessageBox();
    Task DownloadAndExtrationWereSuccessfulMessageBox();
    Task ShowEmulatorDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task ShowCoreDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task ShowImagePackDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task SelectAHistoryItemToRemoveMessageBox();
    Task<MessageBoxResult> ReallyWantToRemoveAllPlayHistoryMessageBox();
    Task SystemAddedMessageBox(string systemName, string resolvedSystemFolder, string resolvedSystemImageFolder);
    Task AddSystemFailedMessageBox(string details = null);
    Task RightClickContextMenuErrorMessageBox();
    Task GameFileDoesNotExistMessageBox();
    Task<MessageBoxResult> GameFileDoesNotExistAskToDeleteMessageBox(string filePath);
    Task<MessageBoxResult> FavoriteFileDoesNotExistAskToDeleteMessageBox(string filePath);
    Task CouldNotOpenHistoryWindowMessageBox();
    Task CouldNotOpenWalkthroughMessageBox();
    Task SelectAFavoriteToRemoveMessageBox();
    Task SystemXmlNotFoundMessageBox();
    Task YouCanAddANewSystemMessageBox();
    Task EmulatorNameRequiredMessageBox(int i);
    Task EmulatorNameIsRequiredMessageBox();
    Task EmulatorNameMustBeUniqueMessageBox(string emulatorName);
    Task SystemSavedSuccessfullyMessageBox();
    Task PathOrParameterInvalidMessageBox();
    Task Emulator1RequiredMessageBox();
    Task ExtensionToLaunchIsRequiredMessageBox();
    Task ExtensionToSearchIsRequiredMessageBox();
    Task FileMustBeCompressedMessageBox();
    Task SystemImageFolderCanNotBeEmptyMessageBox();
    Task SystemFolderCanNotBeEmptyMessageBox();
    Task SystemNameCanNotBeEmptyMessageBox();
    Task InvalidSystemNameCharactersMessageBox(string invalidChars);
    Task InvalidFolderCharactersMessageBox(string invalidChars);
    Task FolderCreationFailedMessageBox();
    Task SelectASystemToDeleteMessageBox();
    Task SystemNotFoundInTheXmlMessageBox();
    Task ErrorFindingGameFilesMessageBox(string logPath);
    Task GamePadErrorMessageBox(string logPath);
    Task CouldNotLaunchGameMessageBox(string logPath);
    Task InvalidOperationExceptionMessageBox(string logPath);
    Task ThereWasAnErrorLaunchingThisGameMessageBox(string logPath);
    Task BatchFileFailedMessageBox(string batchFilePath, string errorDetail, string logPath, int? exitCode = null);
    Task<bool> BatchFilePathsMissingMessageBox(List<string> missingPaths);
    Task ElevationRequiredMessageBox();
    Task NullFileExtensionMessageBox();
    Task CouldNotFindAFileMessageBox();
    Task<MessageBoxResult> SearchOnlineForRomHistoryMessageBox();
    Task SystemHasBeenDeletedMessageBox(string selectedSystemName);
    Task<MessageBoxResult> AreYouSureDoYouWantToDeleteThisSystemMessageBox();
    Task ThereWasAnErrorDeletingTheGameMessageBox();
    Task ThereWasAnErrorDeletingTheCoverImageMessageBox();
    Task<MessageBoxResult> AreYouSureYouWantToDeleteTheGameMessageBox(string fileNameWithExtension);
    Task<MessageBoxResult> AreYouSureYouWantToDeleteTheCoverImageMessageBox(string fileNameWithoutExtension);
    Task<MessageBoxResult> WoulYouLikeToSaveAReportMessageBox();
    Task SimpleLauncherWasUnableToRestoreBackupMessageBox();
    Task<MessageBoxResult> WouldYouLikeToRestoreTheLastBackupMessageBox();
    Task FailedToLoadLanguageResourceMessageBox();
    Task InvalidSystemConfigurationMessageBox(string errorMessage);
    Task UnableToOpenLinkMessageBox();
    Task NoGameFoundInTheRandomSelectionMessageBox();
    Task PleaseSelectASystemBeforeMessageBox();
    Task ToggleFuzzyMatchingFailureMessageBox();
    Task FuzzyMatchingErrorFailToSetThresholdMessageBox();
    Task ListOfErrorsMessageBox(StringBuilder errorMessages);
    Task ThereIsNoUpdateAvailableMessageBox(string currentVersion);
    Task AnotherInstanceIsRunningMessageBox();
    Task FailedToStartSimpleLauncherMessageBox();
    Task FailedToRestartMessageBox();
    Task<MessageBoxResult> DoYouWantToUpdateMessageBox(string currentVersion, string latestVersion);
    Task HandleMissingRequiredFilesMessageBox(string fileList);
    Task HandleApiConfigErrorMessageBox(string reason);
    Task DiskSpaceErrorMessageBox();
    Task CouldNotCheckForDiskSpaceMessageBox();
    Task SaveSystemFailedMessageBox(string details = null);
    Task CouldNotOpenTheDownloadLinkMessageBox();
    Task ErrorLoadingAppSettingsMessageBox();
    Task PotentialPathManipulationDetectedMessageBox(string archivePath);
    Task CouldNotOpenSoundConfigurationWindowMessageBox();
    Task ErrorSettingSoundFileMessageBox();
    Task NotificationSoundIsDisableMessageBox();
    Task NoSoundFileIsSelectedMessageBox();
    Task SettingsSavedSuccessfullyMessageBox();
    Task FailedToSaveSettingsMessageBox();
    Task FilePathIsInvalidMessageBox(string logPath);
    Task ThereWasAnErrorMountingTheFileMessageBox(int? exitCode = null);
    Task DokanDriverNotInstalledMessageBox();
    Task LaunchToolInformationMessageBox(string info);
    Task CannotScreenshotMinimizedWindowMessageBox();
    Task FailedToCopyLogContentMessageBox();
    Task CouldNotFindUpdaterOnGitHubMessageBox();
    Task CouldNotOpenAchievementsWindowMessageBox();
    Task<MessageBoxResult> GameNotSupportedByRetroAchievementsMessageBox();
    Task GameLaunchTimeoutMessageBox();
    Task AddRaLoginMessageBox();
    Task NoDefaultBrowserConfiguredMessageBox();
    Task<MessageBoxResult> WarnUserAboutMemoryConsumptionMessageBox();
    Task GroupByFolderOnlyForMameAndDosBoxMessageBox();
    Task<MessageBoxResult> GroupByFolderWarningMessageBox();
    Task<MessageBoxResult> FirstRunWelcomeMessageBox();
    Task Emulator1LocationRequiredMessageBox();
    Task Emulator2LocationRequiredMessageBox();
    Task Emulator3LocationRequiredMessageBox();
    Task Emulator4LocationRequiredMessageBox();
    Task Emulator5LocationRequiredMessageBox();
    Task ImagePackDownloaderUnavailableMessageBox();
    Task EasyModeUnavailableMessageBox();
    Task SimpleLauncherDoesNotSupportRaHashOfSystemGroupedByFolderMessageBox();
    Task UnsupportedArchitectureMessageBox();
    Task SevenZipDllNotFoundMessageBox();
    Task FailedToInitializeSevenZipMessageBox();
    Task ShowExtractionFailedMessageBoxAsync(string tempFolderPath);
    Task ShowDownloadFileLockedMessageBoxAsync(string tempFolderPath);
    Task ShowCustomMessageBox(string message, string launchError, string logPath);
    Task EnterValidSearchTermsMessageBox();
    Task OperationCancelledMessageBox();
    Task<MessageBoxResult> DoYouWantToCancelAndCloseMessageBox();
    Task CouldNotOpenBrowserForAiSupportMessageBox();
    Task PowerShellExecutionPolicyRestrictionsMessageBox();
    Task UnabletomountIsOfileMessageBox();
    Task UnabletoDismountIsOfileMessageBox();
    Task ApplicationControlPolicyBlockedMessageBox();
    Task ApplicationControlPolicyBlockedManualLinkMessageBox(string url);
    Task EnterYourRetroAchievementsUsernameMessageBox();
    Task EmulatorConfiguredSuccessfullyMessageBox();
    Task FailedToConfigureTheEmulatorMessageBox();
    Task AnErrorOccurredWhileConfiguringTheEmulatorMessageBox();
    Task FailedToLoginToRetroAchievementsMessageBox();
    Task FileSystemXmlIsLockedMessageBox();
    Task FailedToInjectMameConfigurationMessageBox();
    Task MamEconfigurationinjectedsuccessfullyMessageBox();
    Task FailedtoinjectMamEconfiguration2MessageBox();
    Task MameEmulatorPathNotFoundMessageBox();
    Task RetroArchemulatorpathnotfoundMessageBox();
    Task FailedtoinjectRetroArchconfigurationMessageBox();
    Task RetroArchconfigurationinjectedsuccessfullyMessageBox();
    Task FailedtoinjectRetroArchconfiguration2MessageBox();
    Task XeniaemulatorpathnotfoundMessageBox();
    Task FailedtoinjectXeniaconfigurationMessageBox();
    Task XeniaconfigurationinjectedsuccessfullyMessageBox();
    Task FailedtoinjectXeniaconfiguration2MessageBox();
    Task EnterUsernamePasswordMessageBox();
    Task AresemulatornotfoundMessageBox();
    Task DaphnesettingssavedsuccessfullyMessageBox();
    Task Pcsx2SettingssavedMessageBox();
    Task SettingsSavedMessageBox();
    Task CemuemulatornotfoundMessageBox();
    Task FailedtoinjectAresconfigurationMessageBox();
    Task CemuConfigurationSavedMessageBox();
    Task FlycastEmulatorNotFoundMessageBox();
    Task AresConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveAresConfigurationMessageBox();
    Task FailedToInjectFlycastConfigurationMessageBox();
    Task FlycastConfigurationSavedSuccessfullyMessageBox();
    Task DolphinEmulatorNotFoundMessageBox();
    Task FailedToSaveFlycastConfigurationMessageBox();
    Task FailedToInjectDolphinConfigurationMessageBox();
    Task DolphinConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveDolphinConfigurationMessageBox();
    Task SegaModel2EmulatorNotFoundMessageBox();
    Task FailedToInjectSegaModel2ConfigurationMessageBox();
    Task SegaModel2ConfigurationSavedSuccessfullyMessageBox();
    Task BlastemEmulatorNotFoundMessageBox();
    Task FailedToInjectBlastemConfigurationMessageBox();
    Task BlastemConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveSegaModel2ConfigurationMessageBox();
    Task FailedToSaveBlastemConfigurationMessageBox();
    Task Rpcs3EmulatorNotFoundPleaseLocateMessageBox();
    Task FailedToInjectRpcs3ConfigurationMessageBox();
    Task Rpcs3ConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveRpcs3ConfigurationMessageBox();
    Task StellaEmulatorNotFoundMessageBox();
    Task FailedToInjectStellaConfigurationMessageBox();
    Task SupermodelEmulatorNotFoundMessageBox();
    Task StellaConfigurationSavedSuccessfullyMessageBox();
    Task FailedToInjectSupermodelConfigurationMessageBox();
    Task FailedToSaveStellaConfigurationMessageBox();
    Task SupermodelConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveSupermodelConfigurationMessageBox();
    Task MednafenEmulatorNotFoundMessageBox();
    Task MesenEmulatorNotFoundMessageBox();
    Task FailedToInjectMednafenConfigurationMessageBox();
    Task FailedToInjectMesenConfigurationMessageBox();
    Task DuckStationEmulatorNotFoundMessageBox();
    Task MednafenConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveMednafenConfigurationMessageBox();
    Task FailedToInjectDuckStationConfigurationMessageBox();
    Task DuckStationConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveMesenConfigurationMessageBox();
    Task FailedToSaveDuckStationConfigurationMessageBox();
    Task MesenConfigurationSavedSuccessfullyMessageBox();
    Task FailedToInjectYumirConfigurationMessageBox();
    Task YumirConfigurationSavedSuccessfullyMessageBox();
    Task RaineSettingsSavedAndInjectedMessageBox();
    Task RaineExecutableNotFoundMessageBox();
    Task YumirEmulatorNotFoundMessageBox();
    Task ReDreamEmulatorPathNotFoundMessageBox();
    Task FailedToInjectReDreamConfigurationMessageBox();
    Task ReDreamConfigurationInjectedSuccessfullyMessageBox();
    Task CouldNotLaunchGameDueToDepViolationMessageBox();
    Task MameRomSetErrorMessageBox();
    Task MameUnknownSystemErrorMessageBox();
    Task MameUnableToLoadImageMessageBox();
    Task OotakeDoesNotSupportImageFilesMessageBox();
    Task GeolithDoesNotSupportCompressedFilesMessageBox();
    Task RetroArchParameterShouldContainLMessageBox();
    Task RetroArchParameterIssueMessageBox(string logPath);
    Task RetroArchSpecialCharactersInPathMessageBox();
    Task AzaharConfigurationInjectionPermissionErrorMessageBox();
    Task AzaharConfigurationSavedSuccessfullyMessageBox();
    Task FailedToSaveAzaharConfigurationMessageBox();
    Task XemuParameterShouldContainDvdPathMessageBox();
    Task PleaseExtractApplicationFirstMessageBox();
    Task InjectionFailedGenericMessageBox();
    Task DaphneConfigurationSaveFailedMessageBox();
    Task ShowImageDownloadTimeoutMessageBox();
    Task SystemNameRequiredBeforeChoosingImageMessageBox();
    Task InvalidImageFormatMessageBox();
    Task FailedToCopySystemImageMessageBox(string errorMessage);
    Task WarningMessageBox(string message);
    Task CustomErrorMessageBox(string message, string title);
    Task<bool> CustomQuestionMessageBox(string title, string message);
}
