using System.Text;
using SimpleLauncher.Models;

namespace SimpleLauncher.Interfaces;

public interface IMessageBoxLibraryService
{
    Task TakeScreenShotMessageBoxAsync();
    Task CouldNotSaveScreenshotMessageBoxAsync();
    Task GameIsAlreadyInFavoritesMessageBoxAsync(string fileNameWithExtension);
    Task ErrorWhileAddingFavoritesMessageBoxAsync();
    Task ErrorWhileRemovingGameFromFavoriteMessageBoxAsync();
    Task ErrorOpeningTheUpdateHistoryWindowMessageBoxAsync();
    Task ErrorOpeningVideoLinkMessageBoxAsync();
    Task ProblemOpeningInfoLinkMessageBoxAsync();
    Task ErrorOpeningUrlMessageBoxAsync();
    Task ThereIsNoCoverMessageBoxAsync();
    Task ThereIsNoTitleSnapshotMessageBoxAsync();
    Task ThereIsNoGameplaySnapshotMessageBoxAsync();
    Task ThereIsNoCartMessageBoxAsync();
    Task ThereIsNoVideoFileMessageBoxAsync();
    Task CouldNotOpenManualMessageBoxAsync();
    Task NoPdfViewerInstalledMessageBoxAsync();
    Task ThereIsNoManualMessageBoxAsync();
    Task ThereIsNoWalkthroughMessageBoxAsync();
    Task ThereIsNoCabinetMessageBoxAsync();
    Task ThereIsNoFlyerMessageBoxAsync();
    Task ThereIsNoPcbMessageBoxAsync();
    Task FileSuccessfullyDeletedMessageBoxAsync(string fileNameWithExtension);
    Task FileCouldNotBeDeletedMessageBoxAsync(string fileNameWithExtension);
    Task DefaultImageNotFoundMessageBoxAsync();
    Task GlobalSearchErrorMessageBoxAsync();
    Task PleaseEnterSearchTermMessageBoxAsync();
    Task ErrorLaunchingGameMessageBoxAsync(string logPath);
    Task SelectAGameToLaunchMessageBoxAsync();
    Task FileAddedToFavoritesMessageBoxAsync(string fileNameWithoutExtension);
    Task FileRemovedFromFavoritesMessageBoxAsync(string fileNameWithoutExtension);
    Task CouldNotLaunchThisGameMessageBoxAsync(string logPath);
    Task ProtocolHandlerNotRegisteredMessageBoxAsync(string protocol);
    Task EmulatorPathNotConfiguredMessageBoxAsync();
    Task ErrorCalculatingStatsMessageBoxAsync();
    Task FailedSaveReportMessageBoxAsync();
    Task ReportSavedMessageBoxAsync();
    Task NoStatsToSaveMessageBoxAsync();
    Task ErrorLaunchingToolMessageBoxAsync(string logPath);
    Task SelectedToolNotFoundMessageBoxAsync();
    Task ErrorMessageBoxAsync();
    Task NoFavoriteFoundMessageBoxAsync();
    Task MoveToWritableFolderMessageBoxAsync();
    Task InvalidSystemConfigMessageBoxAsync();
    Task ErrorMethodLoadGameFilesAsyncMessageBoxAsync();
    Task ErrorOpeningDonationLinkMessageBoxAsync();
    Task ToggleGamepadFailureMessageBoxAsync();
    Task ToolLaunchWasCanceledByUserMessageBoxAsync();
    Task ErrorChangingViewModeMessageBoxAsync();
    Task NavigationButtonErrorMessageBoxAsync();
    Task SelectSystemBeforeSearchMessageBoxAsync();
    Task EnterSearchQueryMessageBoxAsync();
    Task ErrorWhileLoadingHelpUserXmlMessageBoxAsync();
    Task NoSystemInHelpUserXmlMessageBoxAsync();
    Task<MessageBoxResult> CouldNotLoadHelpUserXmlMessageBoxAsync();
    Task FailedToLoadHelpUserXmlMessageBoxAsync();
    Task FileHelpUserXmlIsMissingMessageBoxAsync();
    Task ErrorWhileLoadingParametersMdMessageBoxAsync();
    Task NoSystemInParametersMdMessageBoxAsync();
    Task FailedToLoadParametersMdMessageBoxAsync();
    Task FileParametersMdIsMissingMessageBoxAsync();
    Task FileParametersMdIsEmptyMessageBoxAsync();
    Task ImageViewerErrorMessageBoxAsync();
    Task ReinstallSimpleLauncherFileCorruptedMessageBoxAsync();
    Task ReinstallSimpleLauncherFileMissingMessageBoxAsync();
    Task ErrorCheckingForUpdatesMessageBoxAsync();
    Task ErrorLoadingRomHistoryMessageBoxAsync();
    Task NoHistoryXmlOrDatFoundMessageBoxAsync();
    Task ErrorOpeningBrowserMessageBoxAsync();
    Task SystemXmlIsCorruptedMessageBoxAsync(string logPath);
    Task WouldYouLikeToOpenTheLogMessageBoxAsync(string logPath);
    Task FileSystemXmlIsCorruptedMessageBoxAsync(string logPath);
    Task InstallUpdateManuallyMessageBoxAsync();
    Task UpdaterLaunchFailedMessageBoxAsync();
    Task RequiredFileMissingMessageBoxAsync();
    Task EnterSupportRequestMessageBoxAsync();
    Task EnterNameMessageBoxAsync();
    Task EnterEmailMessageBoxAsync();
    Task ApiKeyErrorMessageBoxAsync();
    Task SupportRequestSuccessMessageBoxAsync();
    Task SupportRequestSendErrorMessageBoxAsync();
    Task ExtractionFailedMessageBoxAsync();
    Task FileNeedToBeCompressedMessageBoxAsync();
    Task DownloadedFileIsMissingMessageBoxAsync();
    Task FileIsLockedMessageBoxAsync(string tempFolderPath);
    Task LinksSavedMessageBoxAsync();
    Task DeadZonesSavedMessageBoxAsync();
    Task LinksRevertedMessageBoxAsync();
    Task MainWindowSearchEngineErrorMessageBoxAsync();
    Task DownloadExtractionFailedMessageBoxAsync();
    Task DownloadAndExtractionWereSuccessfulMessageBoxAsync();
    Task ShowEmulatorDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task ShowCoreDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task ShowImagePackDownloadErrorMessageBoxAsync(EasyModeSystemConfig selectedSystem);
    Task SelectAHistoryItemToRemoveMessageBoxAsync();
    Task<MessageBoxResult> ReallyWantToRemoveAllPlayHistoryMessageBoxAsync();
    Task SystemAddedMessageBoxAsync(string systemName, string resolvedSystemFolder, string resolvedSystemImageFolder);
    Task AddSystemFailedMessageBoxAsync(string details = null);
    Task RightClickContextMenuErrorMessageBoxAsync();
    Task GameFileDoesNotExistMessageBoxAsync();
    Task<MessageBoxResult> GameFileDoesNotExistAskToDeleteMessageBoxAsync(string filePath);
    Task<MessageBoxResult> FavoriteFileDoesNotExistAskToDeleteMessageBoxAsync(string filePath);
    Task CouldNotOpenHistoryWindowMessageBoxAsync();
    Task CouldNotOpenWalkthroughMessageBoxAsync();
    Task SelectAFavoriteToRemoveMessageBoxAsync();
    Task SystemXmlNotFoundMessageBoxAsync();
    Task YouCanAddANewSystemMessageBoxAsync();
    Task EmulatorNameRequiredMessageBoxAsync(int i);
    Task EmulatorNameIsRequiredMessageBoxAsync();
    Task EmulatorNameMustBeUniqueMessageBoxAsync(string emulatorName);
    Task SystemSavedSuccessfullyMessageBoxAsync();
    Task PathOrParameterInvalidMessageBoxAsync();
    Task Emulator1RequiredMessageBoxAsync();
    Task ExtensionToLaunchIsRequiredMessageBoxAsync();
    Task ExtensionToSearchIsRequiredMessageBoxAsync();
    Task FileMustBeCompressedMessageBoxAsync();
    Task SystemImageFolderCanNotBeEmptyMessageBoxAsync();
    Task SystemFolderCanNotBeEmptyMessageBoxAsync();
    Task SystemNameCanNotBeEmptyMessageBoxAsync();
    Task InvalidSystemNameCharactersMessageBoxAsync(string invalidChars);
    Task InvalidFolderCharactersMessageBoxAsync(string invalidChars);
    Task FolderCreationFailedMessageBoxAsync();
    Task SelectASystemToDeleteMessageBoxAsync();
    Task SystemNotFoundInTheXmlMessageBoxAsync();
    Task ErrorFindingGameFilesMessageBoxAsync(string logPath);
    Task GamePadErrorMessageBoxAsync(string logPath);
    Task CouldNotLaunchGameMessageBoxAsync(string logPath);
    Task InvalidOperationExceptionMessageBoxAsync(string logPath);
    Task ThereWasAnErrorLaunchingThisGameMessageBoxAsync(string logPath);
    Task BatchFileFailedMessageBoxAsync(string batchFilePath, string errorDetail, string logPath, int? exitCode = null);
    Task<bool> BatchFilePathsMissingMessageBoxAsync(List<string> missingPaths);
    Task ElevationRequiredMessageBoxAsync();
    Task NullFileExtensionMessageBoxAsync();
    Task CouldNotFindAFileMessageBoxAsync();
    Task<MessageBoxResult> SearchOnlineForRomHistoryMessageBoxAsync();
    Task SystemHasBeenDeletedMessageBoxAsync(string selectedSystemName);
    Task<MessageBoxResult> AreYouSureDoYouWantToDeleteThisSystemMessageBoxAsync();
    Task ThereWasAnErrorDeletingTheGameMessageBoxAsync();
    Task ThereWasAnErrorDeletingTheCoverImageMessageBoxAsync();
    Task<MessageBoxResult> AreYouSureYouWantToDeleteTheGameMessageBoxAsync(string fileNameWithExtension);
    Task<MessageBoxResult> AreYouSureYouWantToDeleteTheCoverImageMessageBoxAsync(string fileNameWithoutExtension);
    Task<MessageBoxResult> WouldYouLikeToSaveAReportMessageBoxAsync();
    Task SimpleLauncherWasUnableToRestoreBackupMessageBoxAsync();
    Task<MessageBoxResult> WouldYouLikeToRestoreTheLastBackupMessageBoxAsync();
    Task FailedToLoadLanguageResourceMessageBoxAsync();
    Task InvalidSystemConfigurationMessageBoxAsync(string errorMessage);
    Task UnableToOpenLinkMessageBoxAsync();
    Task NoGameFoundInTheRandomSelectionMessageBoxAsync();
    Task PleaseSelectASystemBeforeMessageBoxAsync();
    Task ToggleFuzzyMatchingFailureMessageBoxAsync();
    Task FuzzyMatchingErrorFailToSetThresholdMessageBoxAsync();
    Task ListOfErrorsMessageBoxAsync(StringBuilder errorMessages);
    Task ThereIsNoUpdateAvailableMessageBoxAsync(string currentVersion);
    Task AnotherInstanceIsRunningMessageBoxAsync();
    Task FailedToStartSimpleLauncherMessageBoxAsync();
    Task FailedToRestartMessageBoxAsync();
    Task<MessageBoxResult> DoYouWantToUpdateMessageBoxAsync(string currentVersion, string latestVersion);
    Task HandleMissingRequiredFilesMessageBoxAsync(string fileList);
    Task HandleApiConfigErrorMessageBoxAsync(string reason);
    Task DiskSpaceErrorMessageBoxAsync();
    Task CouldNotCheckForDiskSpaceMessageBoxAsync();
    Task SaveSystemFailedMessageBoxAsync(string details = null);
    Task CouldNotOpenTheDownloadLinkMessageBoxAsync();
    Task ErrorLoadingAppSettingsMessageBoxAsync();
    Task PotentialPathManipulationDetectedMessageBoxAsync(string archivePath);
    Task CouldNotOpenSoundConfigurationWindowMessageBoxAsync();
    Task ErrorSettingSoundFileMessageBoxAsync();
    Task NotificationSoundIsDisableMessageBoxAsync();
    Task NoSoundFileIsSelectedMessageBoxAsync();
    Task SettingsSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveSettingsMessageBoxAsync();
    Task FilePathIsInvalidMessageBoxAsync(string logPath);
    Task ThereWasAnErrorMountingTheFileMessageBoxAsync(int? exitCode = null);
    Task DokanDriverNotInstalledMessageBoxAsync();
    Task LaunchToolInformationMessageBoxAsync(string info);
    Task CannotScreenshotMinimizedWindowMessageBoxAsync();
    Task FailedToCopyLogContentMessageBoxAsync();
    Task CouldNotFindUpdaterOnGitHubMessageBoxAsync();
    Task CouldNotOpenAchievementsWindowMessageBoxAsync();
    Task<MessageBoxResult> GameNotSupportedByRetroAchievementsMessageBoxAsync();
    Task GameLaunchTimeoutMessageBoxAsync();
    Task AddRaLoginMessageBoxAsync();
    Task NoDefaultBrowserConfiguredMessageBoxAsync();
    Task<MessageBoxResult> WarnUserAboutMemoryConsumptionMessageBoxAsync();
    Task GroupByFolderOnlyForMameAndDosBoxMessageBoxAsync();
    Task<MessageBoxResult> GroupByFolderWarningMessageBoxAsync();
    Task<MessageBoxResult> FirstRunWelcomeMessageBoxAsync();
    Task Emulator1LocationRequiredMessageBoxAsync();
    Task Emulator2LocationRequiredMessageBoxAsync();
    Task Emulator3LocationRequiredMessageBoxAsync();
    Task Emulator4LocationRequiredMessageBoxAsync();
    Task Emulator5LocationRequiredMessageBoxAsync();
    Task ImagePackDownloaderUnavailableMessageBoxAsync();
    Task EasyModeUnavailableMessageBoxAsync();
    Task SimpleLauncherDoesNotSupportRaHashOfSystemGroupedByFolderMessageBoxAsync();
    Task UnsupportedArchitectureMessageBoxAsync();
    Task SevenZipDllNotFoundMessageBoxAsync();
    Task FailedToInitializeSevenZipMessageBoxAsync();
    Task ShowExtractionFailedMessageBoxAsync(string tempFolderPath);
    Task ShowDownloadFileLockedMessageBoxAsync(string tempFolderPath);
    Task ShowCustomMessageBoxAsync(string message, string launchError, string logPath);
    Task EnterValidSearchTermsMessageBoxAsync();
    Task OperationCancelledMessageBoxAsync();
    Task<MessageBoxResult> DoYouWantToCancelAndCloseMessageBoxAsync();
    Task CouldNotOpenBrowserForAiSupportMessageBoxAsync();
    Task PowerShellExecutionPolicyRestrictionsMessageBoxAsync();
    Task UnabletomountIsOfileMessageBoxAsync();
    Task UnabletoDismountIsOfileMessageBoxAsync();
    Task ApplicationControlPolicyBlockedMessageBoxAsync();
    Task ApplicationControlPolicyBlockedManualLinkMessageBoxAsync(string url);
    Task EnterYourRetroAchievementsUsernameMessageBoxAsync();
    Task EmulatorConfiguredSuccessfullyMessageBoxAsync();
    Task FailedToConfigureTheEmulatorMessageBoxAsync();
    Task AnErrorOccurredWhileConfiguringTheEmulatorMessageBoxAsync();
    Task FailedToLoginToRetroAchievementsMessageBoxAsync();
    Task FileSystemXmlIsLockedMessageBoxAsync();
    Task FailedToInjectMameConfigurationMessageBoxAsync();
    Task MameConfigurationInjectedSuccessfullyMessageBoxAsync();
    Task FailedtoinjectMamEconfiguration2MessageBoxAsync();
    Task MameEmulatorPathNotFoundMessageBoxAsync();
    Task RetroArchemulatorpathnotfoundMessageBoxAsync();
    Task FailedtoinjectRetroArchconfigurationMessageBoxAsync();
    Task RetroArchConfigurationInjectedSuccessfullyMessageBoxAsync();
    Task FailedtoinjectRetroArchconfiguration2MessageBoxAsync();
    Task XeniaemulatorpathnotfoundMessageBoxAsync();
    Task FailedtoinjectXeniaconfigurationMessageBoxAsync();
    Task XeniaconfigurationinjectedsuccessfullyMessageBoxAsync();
    Task FailedtoinjectXeniaconfiguration2MessageBoxAsync();
    Task EnterUsernamePasswordMessageBoxAsync();
    Task AresemulatornotfoundMessageBoxAsync();
    Task DaphnesettingssavedsuccessfullyMessageBoxAsync();
    Task Pcsx2SettingssavedMessageBoxAsync();
    Task Pcsx2ConfigurationInjectionPermissionErrorMessageBoxAsync();
    Task SettingsSavedMessageBoxAsync();
    Task CemuEmulatorNotFoundMessageBoxAsync();
    Task FailedtoinjectAresconfigurationMessageBoxAsync();
    Task CemuConfigurationSavedMessageBoxAsync();
    Task FlycastEmulatorNotFoundMessageBoxAsync();
    Task AresConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveAresConfigurationMessageBoxAsync();
    Task FailedToInjectFlycastConfigurationMessageBoxAsync();
    Task FlycastConfigurationSavedSuccessfullyMessageBoxAsync();
    Task DolphinEmulatorNotFoundMessageBoxAsync();
    Task FailedToSaveFlycastConfigurationMessageBoxAsync();
    Task FailedToInjectDolphinConfigurationMessageBoxAsync();
    Task DolphinConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveDolphinConfigurationMessageBoxAsync();
    Task SegaModel2EmulatorNotFoundMessageBoxAsync();
    Task FailedToInjectSegaModel2ConfigurationMessageBoxAsync();
    Task SegaModel2ConfigurationSavedSuccessfullyMessageBoxAsync();
    Task BlastemEmulatorNotFoundMessageBoxAsync();
    Task FailedToInjectBlastemConfigurationMessageBoxAsync();
    Task BlastemConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveSegaModel2ConfigurationMessageBoxAsync();
    Task FailedToSaveBlastemConfigurationMessageBoxAsync();
    Task Rpcs3EmulatorNotFoundPleaseLocateMessageBoxAsync();
    Task FailedToInjectRpcs3ConfigurationMessageBoxAsync();
    Task Rpcs3ConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveRpcs3ConfigurationMessageBoxAsync();
    Task StellaEmulatorNotFoundMessageBoxAsync();
    Task FailedToInjectStellaConfigurationMessageBoxAsync();
    Task SupermodelEmulatorNotFoundMessageBoxAsync();
    Task StellaConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToInjectSupermodelConfigurationMessageBoxAsync();
    Task FailedToSaveStellaConfigurationMessageBoxAsync();
    Task SupermodelConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveSupermodelConfigurationMessageBoxAsync();
    Task MednafenEmulatorNotFoundMessageBoxAsync();
    Task MesenEmulatorNotFoundMessageBoxAsync();
    Task FailedToInjectMednafenConfigurationMessageBoxAsync();
    Task FailedToInjectMesenConfigurationMessageBoxAsync();
    Task DuckStationEmulatorNotFoundMessageBoxAsync();
    Task MednafenConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveMednafenConfigurationMessageBoxAsync();
    Task FailedToInjectDuckStationConfigurationMessageBoxAsync();
    Task DuckStationConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveMesenConfigurationMessageBoxAsync();
    Task FailedToSaveDuckStationConfigurationMessageBoxAsync();
    Task MesenConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToInjectYumirConfigurationMessageBoxAsync();
    Task YumirConfigurationSavedSuccessfullyMessageBoxAsync();
    Task RaineSettingsSavedAndInjectedMessageBoxAsync();
    Task RaineExecutableNotFoundMessageBoxAsync();
    Task YumirEmulatorNotFoundMessageBoxAsync();
    Task ReDreamEmulatorPathNotFoundMessageBoxAsync();
    Task FailedToInjectReDreamConfigurationMessageBoxAsync();
    Task ReDreamConfigurationInjectedSuccessfullyMessageBoxAsync();
    Task CouldNotLaunchGameDueToDepViolationMessageBoxAsync();
    Task MameRomSetErrorMessageBoxAsync();
    Task MameUnknownSystemErrorMessageBoxAsync();
    Task MameUnableToLoadImageMessageBoxAsync();
    Task OotakeDoesNotSupportImageFilesMessageBoxAsync();
    Task GeolithDoesNotSupportCompressedFilesMessageBoxAsync();
    Task RetroArchParameterShouldContainLMessageBoxAsync();
    Task RetroArchParameterIssueMessageBoxAsync(string logPath);
    Task RetroArchSpecialCharactersInPathMessageBoxAsync();
    Task AzaharConfigurationInjectionPermissionErrorMessageBoxAsync();
    Task AzaharConfigurationSavedSuccessfullyMessageBoxAsync();
    Task FailedToSaveAzaharConfigurationMessageBoxAsync();
    Task XemuParameterShouldContainDvdPathMessageBoxAsync();
    Task PleaseExtractApplicationFirstMessageBoxAsync();
    Task InjectionFailedGenericMessageBoxAsync();
    Task DaphneConfigurationSaveFailedMessageBoxAsync();
    Task ShowImageDownloadTimeoutMessageBoxAsync();
    Task SystemNameRequiredBeforeChoosingImageMessageBoxAsync();
    Task InvalidImageFormatMessageBoxAsync();
    Task FailedToCopySystemImageMessageBoxAsync(string errorMessage);
    Task WarningMessageBoxAsync(string message);
    Task CustomErrorMessageBoxAsync(string message, string title);
    Task<bool> CustomQuestionMessageBoxAsync(string title, string message);
}
